name: Stargate
main: com.bradenn.stargates.Main
version: 1.0
author: bradencn
website: bradenn.com
api-version: 1.17
commands:
  stargate:
    description: Register a stargate
    usage: /stargate
    aliases: sg
permissions:
  stargate.default:
    default: true
  stargate.create:
    default: op
  stargate.seed:
    default: op
  stargate.remove:
    default: op
  stargate.rebuild:
    default: op
  stargate.purge:
    default: op