name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Deploy to GitHub
      run: mvn --batch-mode -DuseGitHubPackages=true deploy
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
